"use client";

import { Star, X } from "lucide-react";
import { useState } from "react";
import { StarRating } from "@/components/ratings/star-rating";
import { Button } from "@/components/ui/button";
import type { MediaRatingSummary } from "@/types/rating";

export function RatingDialog({ mediaId, summary, onSaved }: { mediaId: string; summary: MediaRatingSummary; onSaved: (summary: MediaRatingSummary) => void }) {
  const [open, setOpen] = useState(false); const [value, setValue] = useState<number | null>(summary.currentUserRating?.rating ?? null); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null);
  async function save() { if (value === null) return; setBusy(true); setError(null); const endpoint = summary.currentUserRating ? `/api/ratings/${summary.currentUserRating.id}` : "/api/ratings"; const response = await fetch(endpoint, { method: summary.currentUserRating ? "PUT" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(summary.currentUserRating ? { rating: value } : { mediaId, rating: value }) }); const payload = await response.json() as { rating?: { id: string; rating: number }; summary?: Omit<MediaRatingSummary, "distribution" | "currentUserRating">; error?: string }; setBusy(false); if (!response.ok || !payload.rating || !payload.summary) { setError(payload.error ?? "Could not save rating."); return; } onSaved({ ...summary, ...payload.summary, currentUserRating: payload.rating }); setOpen(false); }
  async function remove() { if (!summary.currentUserRating) return; setBusy(true); const response = await fetch(`/api/ratings/${summary.currentUserRating.id}`, { method: "DELETE" }); const payload = await response.json() as { summary?: Omit<MediaRatingSummary, "distribution" | "currentUserRating">; error?: string }; setBusy(false); if (!response.ok || !payload.summary) { setError(payload.error ?? "Could not remove rating."); return; } onSaved({ ...summary, ...payload.summary, currentUserRating: null }); setValue(null); setOpen(false); }
  return <><Button onClick={() => setOpen(true)} className="bg-amber-400 text-zinc-950 hover:bg-amber-300"><Star className="size-4 fill-current" />{summary.currentUserRating ? `${summary.currentUserRating.rating.toFixed(1)} / 10` : "Rate this title"}</Button>{open && <div className="fixed inset-0 z-50 grid place-items-center bg-black/70 p-4 backdrop-blur-sm" role="dialog" aria-modal="true" aria-label="Rate this title"><div className="w-full max-w-md rounded-2xl border border-amber-400/25 bg-background/95 p-6 shadow-2xl backdrop-blur-xl"><div className="flex items-start justify-between"><div><p className="text-sm font-semibold text-amber-400">Your rating</p><h2 className="mt-1 text-xl font-bold">How did it land for you?</h2></div><Button variant="ghost" size="icon" aria-label="Close rating dialog" onClick={() => setOpen(false)}><X className="size-5" /></Button></div><div className="mt-8 text-center"><StarRating value={value} onChange={setValue} size="lg" /><p className="mt-3 text-lg font-bold">{value?.toFixed(1) ?? "Choose a score"}</p><p className="mt-1 text-sm text-muted-foreground">Community average: {summary.communityAverageRating?.toFixed(1) ?? "—"}</p></div><div className="mt-8 flex gap-3"><Button className="flex-1 bg-amber-400 text-zinc-950 hover:bg-amber-300" disabled={busy || value === null} onClick={save}>{busy ? "Saving…" : "Save rating"}</Button>{summary.currentUserRating && <Button variant="outline" disabled={busy} onClick={remove}>Remove</Button>}</div>{error && <p role="alert" className="mt-3 text-sm text-destructive">{error}</p>}</div></div>}</>;
}
